# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cplugin.proto\"^\n\x14\x43\x61llCommandLikeLogic\x12\x16\n\x06paramA\x18\x01 \x01(\x03R\x06paramA\x12\x16\n\x06paramB\x18\x02 \x01(\x03R\x06paramB\x12\x16\n\x06paramC\x18\x03 \x01(\tR\x06paramC\"\x14\n\x12\x43\x61llDataFrameLogic\"\xaf\x01\n\x1b\x43\x61llObjectManipulationLogic\x12\x1a\n\x08objectId\x18\x01 \x01(\x05R\x08objectId\x12\x1c\n\tnewObject\x18\x02 \x01(\x08R\tnewObject\x12\"\n\x0c\x64\x65leteObject\x18\x03 \x01(\x08R\x0c\x64\x65leteObject\x12\x1e\n\nmethodName\x18\x04 \x01(\tR\nmethodName\x12\x12\n\x04\x61rgs\x18\x05 \x03(\tR\x04\x61rgsB \n\x1c\x63om.ssinchenko.example.protoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'plugin_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\034com.ssinchenko.example.protoP\001'
  _globals['_CALLCOMMANDLIKELOGIC']._serialized_start=16
  _globals['_CALLCOMMANDLIKELOGIC']._serialized_end=110
  _globals['_CALLDATAFRAMELOGIC']._serialized_start=112
  _globals['_CALLDATAFRAMELOGIC']._serialized_end=132
  _globals['_CALLOBJECTMANIPULATIONLOGIC']._serialized_start=135
  _globals['_CALLOBJECTMANIPULATIONLOGIC']._serialized_end=310
# @@protoc_insertion_point(module_scope)
