// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: plugin.proto

package com.ssinchenko.example.proto;

/**
 * Protobuf type {@code example.CallDFObjectCreateDataFrame}
 */
public final class CallDFObjectCreateDataFrame extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:example.CallDFObjectCreateDataFrame)
    CallDFObjectCreateDataFrameOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CallDFObjectCreateDataFrame.newBuilder() to construct.
  private CallDFObjectCreateDataFrame(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CallDFObjectCreateDataFrame() {
    stringPath_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CallDFObjectCreateDataFrame();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ssinchenko.example.proto.Plugin.internal_static_example_CallDFObjectCreateDataFrame_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ssinchenko.example.proto.Plugin.internal_static_example_CallDFObjectCreateDataFrame_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ssinchenko.example.proto.CallDFObjectCreateDataFrame.class, com.ssinchenko.example.proto.CallDFObjectCreateDataFrame.Builder.class);
  }

  public static final int STRINGPATH_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object stringPath_ = "";
  /**
   * <code>string stringPath = 1;</code>
   * @return The stringPath.
   */
  @java.lang.Override
  public java.lang.String getStringPath() {
    java.lang.Object ref = stringPath_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      stringPath_ = s;
      return s;
    }
  }
  /**
   * <code>string stringPath = 1;</code>
   * @return The bytes for stringPath.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStringPathBytes() {
    java.lang.Object ref = stringPath_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      stringPath_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(stringPath_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, stringPath_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(stringPath_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, stringPath_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ssinchenko.example.proto.CallDFObjectCreateDataFrame)) {
      return super.equals(obj);
    }
    com.ssinchenko.example.proto.CallDFObjectCreateDataFrame other = (com.ssinchenko.example.proto.CallDFObjectCreateDataFrame) obj;

    if (!getStringPath()
        .equals(other.getStringPath())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STRINGPATH_FIELD_NUMBER;
    hash = (53 * hash) + getStringPath().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ssinchenko.example.proto.CallDFObjectCreateDataFrame parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ssinchenko.example.proto.CallDFObjectCreateDataFrame parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ssinchenko.example.proto.CallDFObjectCreateDataFrame parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ssinchenko.example.proto.CallDFObjectCreateDataFrame parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ssinchenko.example.proto.CallDFObjectCreateDataFrame parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ssinchenko.example.proto.CallDFObjectCreateDataFrame parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ssinchenko.example.proto.CallDFObjectCreateDataFrame parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ssinchenko.example.proto.CallDFObjectCreateDataFrame parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.ssinchenko.example.proto.CallDFObjectCreateDataFrame parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.ssinchenko.example.proto.CallDFObjectCreateDataFrame parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ssinchenko.example.proto.CallDFObjectCreateDataFrame parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ssinchenko.example.proto.CallDFObjectCreateDataFrame parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ssinchenko.example.proto.CallDFObjectCreateDataFrame prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code example.CallDFObjectCreateDataFrame}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:example.CallDFObjectCreateDataFrame)
      com.ssinchenko.example.proto.CallDFObjectCreateDataFrameOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ssinchenko.example.proto.Plugin.internal_static_example_CallDFObjectCreateDataFrame_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ssinchenko.example.proto.Plugin.internal_static_example_CallDFObjectCreateDataFrame_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ssinchenko.example.proto.CallDFObjectCreateDataFrame.class, com.ssinchenko.example.proto.CallDFObjectCreateDataFrame.Builder.class);
    }

    // Construct using com.ssinchenko.example.proto.CallDFObjectCreateDataFrame.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      stringPath_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ssinchenko.example.proto.Plugin.internal_static_example_CallDFObjectCreateDataFrame_descriptor;
    }

    @java.lang.Override
    public com.ssinchenko.example.proto.CallDFObjectCreateDataFrame getDefaultInstanceForType() {
      return com.ssinchenko.example.proto.CallDFObjectCreateDataFrame.getDefaultInstance();
    }

    @java.lang.Override
    public com.ssinchenko.example.proto.CallDFObjectCreateDataFrame build() {
      com.ssinchenko.example.proto.CallDFObjectCreateDataFrame result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ssinchenko.example.proto.CallDFObjectCreateDataFrame buildPartial() {
      com.ssinchenko.example.proto.CallDFObjectCreateDataFrame result = new com.ssinchenko.example.proto.CallDFObjectCreateDataFrame(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.ssinchenko.example.proto.CallDFObjectCreateDataFrame result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.stringPath_ = stringPath_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ssinchenko.example.proto.CallDFObjectCreateDataFrame) {
        return mergeFrom((com.ssinchenko.example.proto.CallDFObjectCreateDataFrame)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ssinchenko.example.proto.CallDFObjectCreateDataFrame other) {
      if (other == com.ssinchenko.example.proto.CallDFObjectCreateDataFrame.getDefaultInstance()) return this;
      if (!other.getStringPath().isEmpty()) {
        stringPath_ = other.stringPath_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              stringPath_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object stringPath_ = "";
    /**
     * <code>string stringPath = 1;</code>
     * @return The stringPath.
     */
    public java.lang.String getStringPath() {
      java.lang.Object ref = stringPath_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stringPath_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string stringPath = 1;</code>
     * @return The bytes for stringPath.
     */
    public com.google.protobuf.ByteString
        getStringPathBytes() {
      java.lang.Object ref = stringPath_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stringPath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string stringPath = 1;</code>
     * @param value The stringPath to set.
     * @return This builder for chaining.
     */
    public Builder setStringPath(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      stringPath_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string stringPath = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearStringPath() {
      stringPath_ = getDefaultInstance().getStringPath();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string stringPath = 1;</code>
     * @param value The bytes for stringPath to set.
     * @return This builder for chaining.
     */
    public Builder setStringPathBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      stringPath_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:example.CallDFObjectCreateDataFrame)
  }

  // @@protoc_insertion_point(class_scope:example.CallDFObjectCreateDataFrame)
  private static final com.ssinchenko.example.proto.CallDFObjectCreateDataFrame DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ssinchenko.example.proto.CallDFObjectCreateDataFrame();
  }

  public static com.ssinchenko.example.proto.CallDFObjectCreateDataFrame getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CallDFObjectCreateDataFrame>
      PARSER = new com.google.protobuf.AbstractParser<CallDFObjectCreateDataFrame>() {
    @java.lang.Override
    public CallDFObjectCreateDataFrame parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CallDFObjectCreateDataFrame> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CallDFObjectCreateDataFrame> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ssinchenko.example.proto.CallDFObjectCreateDataFrame getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

