// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: plugin.proto

package com.ssinchenko.example.proto;

public interface CallDFObjectCreateDataFrameOrBuilder extends
    // @@protoc_insertion_point(interface_extends:example.CallDFObjectCreateDataFrame)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string stringPath = 1;</code>
   * @return The stringPath.
   */
  java.lang.String getStringPath();
  /**
   * <code>string stringPath = 1;</code>
   * @return The bytes for stringPath.
   */
  com.google.protobuf.ByteString
      getStringPathBytes();
}
