// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: plugin.proto

package com.ssinchenko.example.proto;

public final class Plugin {
  private Plugin() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_example_CallDFObjectCreateDataFrame_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_example_CallDFObjectCreateDataFrame_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014plugin.proto\022\007example\"1\n\033CallDFObjectC" +
      "reateDataFrame\022\022\n\nstringPath\030\001 \001(\tB \n\034co" +
      "m.ssinchenko.example.protoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_example_CallDFObjectCreateDataFrame_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_example_CallDFObjectCreateDataFrame_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_example_CallDFObjectCreateDataFrame_descriptor,
        new java.lang.String[] { "StringPath", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
