"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class CallCommandLikeLogic(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PARAMA_FIELD_NUMBER: builtins.int
    PARAMB_FIELD_NUMBER: builtins.int
    PARAMC_FIELD_NUMBER: builtins.int
    paramA: builtins.int
    paramB: builtins.int
    paramC: builtins.str
    def __init__(
        self,
        *,
        paramA: builtins.int = ...,
        paramB: builtins.int = ...,
        paramC: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["paramA", b"paramA", "paramB", b"paramB", "paramC", b"paramC"]) -> None: ...

global___CallCommandLikeLogic = CallCommandLikeLogic

@typing_extensions.final
class CallDataFrameLogic(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___CallDataFrameLogic = CallDataFrameLogic

@typing_extensions.final
class CallObjectManipulationLogic(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OBJECTID_FIELD_NUMBER: builtins.int
    NEWOBJECT_FIELD_NUMBER: builtins.int
    DELETEOBJECT_FIELD_NUMBER: builtins.int
    METHODNAME_FIELD_NUMBER: builtins.int
    ARGS_FIELD_NUMBER: builtins.int
    objectId: builtins.int
    newObject: builtins.bool
    deleteObject: builtins.bool
    methodName: builtins.str
    @property
    def args(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        objectId: builtins.int = ...,
        newObject: builtins.bool = ...,
        deleteObject: builtins.bool = ...,
        methodName: builtins.str = ...,
        args: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["args", b"args", "deleteObject", b"deleteObject", "methodName", b"methodName", "newObject", b"newObject", "objectId", b"objectId"]) -> None: ...

global___CallObjectManipulationLogic = CallObjectManipulationLogic
