// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: plugin.proto

// Protobuf Java Version: 3.25.3
package com.ssinchenko.example.proto;

public interface CallCommandLikeLogicOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CallCommandLikeLogic)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 paramA = 1 [json_name = "paramA"];</code>
   * @return The paramA.
   */
  long getParamA();

  /**
   * <code>int64 paramB = 2 [json_name = "paramB"];</code>
   * @return The paramB.
   */
  long getParamB();

  /**
   * <code>string paramC = 3 [json_name = "paramC"];</code>
   * @return The paramC.
   */
  java.lang.String getParamC();
  /**
   * <code>string paramC = 3 [json_name = "paramC"];</code>
   * @return The bytes for paramC.
   */
  com.google.protobuf.ByteString
      getParamCBytes();
}
