// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example/plugin.proto

// Protobuf Java Version: 3.25.3
package com.ssinchenko.example.proto;

/**
 * Protobuf type {@code example.CallCommandLikeLogic}
 */
public final class CallCommandLikeLogic extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:example.CallCommandLikeLogic)
    CallCommandLikeLogicOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CallCommandLikeLogic.newBuilder() to construct.
  private CallCommandLikeLogic(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CallCommandLikeLogic() {
    paramC_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CallCommandLikeLogic();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ssinchenko.example.proto.Plugin.internal_static_example_CallCommandLikeLogic_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ssinchenko.example.proto.Plugin.internal_static_example_CallCommandLikeLogic_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ssinchenko.example.proto.CallCommandLikeLogic.class, com.ssinchenko.example.proto.CallCommandLikeLogic.Builder.class);
  }

  public static final int PARAMA_FIELD_NUMBER = 1;
  private long paramA_ = 0L;
  /**
   * <code>int64 paramA = 1 [json_name = "paramA"];</code>
   * @return The paramA.
   */
  @java.lang.Override
  public long getParamA() {
    return paramA_;
  }

  public static final int PARAMB_FIELD_NUMBER = 2;
  private long paramB_ = 0L;
  /**
   * <code>int64 paramB = 2 [json_name = "paramB"];</code>
   * @return The paramB.
   */
  @java.lang.Override
  public long getParamB() {
    return paramB_;
  }

  public static final int PARAMC_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object paramC_ = "";
  /**
   * <code>string paramC = 3 [json_name = "paramC"];</code>
   * @return The paramC.
   */
  @java.lang.Override
  public java.lang.String getParamC() {
    java.lang.Object ref = paramC_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      paramC_ = s;
      return s;
    }
  }
  /**
   * <code>string paramC = 3 [json_name = "paramC"];</code>
   * @return The bytes for paramC.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getParamCBytes() {
    java.lang.Object ref = paramC_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      paramC_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (paramA_ != 0L) {
      output.writeInt64(1, paramA_);
    }
    if (paramB_ != 0L) {
      output.writeInt64(2, paramB_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(paramC_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, paramC_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (paramA_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, paramA_);
    }
    if (paramB_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, paramB_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(paramC_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, paramC_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ssinchenko.example.proto.CallCommandLikeLogic)) {
      return super.equals(obj);
    }
    com.ssinchenko.example.proto.CallCommandLikeLogic other = (com.ssinchenko.example.proto.CallCommandLikeLogic) obj;

    if (getParamA()
        != other.getParamA()) return false;
    if (getParamB()
        != other.getParamB()) return false;
    if (!getParamC()
        .equals(other.getParamC())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PARAMA_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getParamA());
    hash = (37 * hash) + PARAMB_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getParamB());
    hash = (37 * hash) + PARAMC_FIELD_NUMBER;
    hash = (53 * hash) + getParamC().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ssinchenko.example.proto.CallCommandLikeLogic parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ssinchenko.example.proto.CallCommandLikeLogic parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ssinchenko.example.proto.CallCommandLikeLogic parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ssinchenko.example.proto.CallCommandLikeLogic parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ssinchenko.example.proto.CallCommandLikeLogic parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ssinchenko.example.proto.CallCommandLikeLogic parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ssinchenko.example.proto.CallCommandLikeLogic parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ssinchenko.example.proto.CallCommandLikeLogic parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.ssinchenko.example.proto.CallCommandLikeLogic parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.ssinchenko.example.proto.CallCommandLikeLogic parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ssinchenko.example.proto.CallCommandLikeLogic parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ssinchenko.example.proto.CallCommandLikeLogic parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ssinchenko.example.proto.CallCommandLikeLogic prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code example.CallCommandLikeLogic}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:example.CallCommandLikeLogic)
      com.ssinchenko.example.proto.CallCommandLikeLogicOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ssinchenko.example.proto.Plugin.internal_static_example_CallCommandLikeLogic_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ssinchenko.example.proto.Plugin.internal_static_example_CallCommandLikeLogic_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ssinchenko.example.proto.CallCommandLikeLogic.class, com.ssinchenko.example.proto.CallCommandLikeLogic.Builder.class);
    }

    // Construct using com.ssinchenko.example.proto.CallCommandLikeLogic.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      paramA_ = 0L;
      paramB_ = 0L;
      paramC_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ssinchenko.example.proto.Plugin.internal_static_example_CallCommandLikeLogic_descriptor;
    }

    @java.lang.Override
    public com.ssinchenko.example.proto.CallCommandLikeLogic getDefaultInstanceForType() {
      return com.ssinchenko.example.proto.CallCommandLikeLogic.getDefaultInstance();
    }

    @java.lang.Override
    public com.ssinchenko.example.proto.CallCommandLikeLogic build() {
      com.ssinchenko.example.proto.CallCommandLikeLogic result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ssinchenko.example.proto.CallCommandLikeLogic buildPartial() {
      com.ssinchenko.example.proto.CallCommandLikeLogic result = new com.ssinchenko.example.proto.CallCommandLikeLogic(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.ssinchenko.example.proto.CallCommandLikeLogic result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.paramA_ = paramA_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.paramB_ = paramB_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.paramC_ = paramC_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ssinchenko.example.proto.CallCommandLikeLogic) {
        return mergeFrom((com.ssinchenko.example.proto.CallCommandLikeLogic)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ssinchenko.example.proto.CallCommandLikeLogic other) {
      if (other == com.ssinchenko.example.proto.CallCommandLikeLogic.getDefaultInstance()) return this;
      if (other.getParamA() != 0L) {
        setParamA(other.getParamA());
      }
      if (other.getParamB() != 0L) {
        setParamB(other.getParamB());
      }
      if (!other.getParamC().isEmpty()) {
        paramC_ = other.paramC_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              paramA_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              paramB_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              paramC_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long paramA_ ;
    /**
     * <code>int64 paramA = 1 [json_name = "paramA"];</code>
     * @return The paramA.
     */
    @java.lang.Override
    public long getParamA() {
      return paramA_;
    }
    /**
     * <code>int64 paramA = 1 [json_name = "paramA"];</code>
     * @param value The paramA to set.
     * @return This builder for chaining.
     */
    public Builder setParamA(long value) {

      paramA_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 paramA = 1 [json_name = "paramA"];</code>
     * @return This builder for chaining.
     */
    public Builder clearParamA() {
      bitField0_ = (bitField0_ & ~0x00000001);
      paramA_ = 0L;
      onChanged();
      return this;
    }

    private long paramB_ ;
    /**
     * <code>int64 paramB = 2 [json_name = "paramB"];</code>
     * @return The paramB.
     */
    @java.lang.Override
    public long getParamB() {
      return paramB_;
    }
    /**
     * <code>int64 paramB = 2 [json_name = "paramB"];</code>
     * @param value The paramB to set.
     * @return This builder for chaining.
     */
    public Builder setParamB(long value) {

      paramB_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int64 paramB = 2 [json_name = "paramB"];</code>
     * @return This builder for chaining.
     */
    public Builder clearParamB() {
      bitField0_ = (bitField0_ & ~0x00000002);
      paramB_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object paramC_ = "";
    /**
     * <code>string paramC = 3 [json_name = "paramC"];</code>
     * @return The paramC.
     */
    public java.lang.String getParamC() {
      java.lang.Object ref = paramC_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        paramC_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string paramC = 3 [json_name = "paramC"];</code>
     * @return The bytes for paramC.
     */
    public com.google.protobuf.ByteString
        getParamCBytes() {
      java.lang.Object ref = paramC_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        paramC_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string paramC = 3 [json_name = "paramC"];</code>
     * @param value The paramC to set.
     * @return This builder for chaining.
     */
    public Builder setParamC(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      paramC_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string paramC = 3 [json_name = "paramC"];</code>
     * @return This builder for chaining.
     */
    public Builder clearParamC() {
      paramC_ = getDefaultInstance().getParamC();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string paramC = 3 [json_name = "paramC"];</code>
     * @param value The bytes for paramC to set.
     * @return This builder for chaining.
     */
    public Builder setParamCBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      paramC_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:example.CallCommandLikeLogic)
  }

  // @@protoc_insertion_point(class_scope:example.CallCommandLikeLogic)
  private static final com.ssinchenko.example.proto.CallCommandLikeLogic DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ssinchenko.example.proto.CallCommandLikeLogic();
  }

  public static com.ssinchenko.example.proto.CallCommandLikeLogic getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CallCommandLikeLogic>
      PARSER = new com.google.protobuf.AbstractParser<CallCommandLikeLogic>() {
    @java.lang.Override
    public CallCommandLikeLogic parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CallCommandLikeLogic> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CallCommandLikeLogic> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ssinchenko.example.proto.CallCommandLikeLogic getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

