// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: plugin.proto

// Protobuf Java Version: 3.25.3
package com.ssinchenko.example.proto;

public interface CallDataFrameLogicOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CallDataFrameLogic)
    com.google.protobuf.MessageOrBuilder {
}
