// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: plugin.proto

// Protobuf Java Version: 3.25.3
package com.ssinchenko.example.proto;

public final class Plugin {
  private Plugin() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CallCommandLikeLogic_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CallCommandLikeLogic_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CallDataFrameLogic_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CallDataFrameLogic_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CallObjectManipulationLogic_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CallObjectManipulationLogic_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014plugin.proto\"^\n\024CallCommandLikeLogic\022\026" +
      "\n\006paramA\030\001 \001(\003R\006paramA\022\026\n\006paramB\030\002 \001(\003R\006" +
      "paramB\022\026\n\006paramC\030\003 \001(\tR\006paramC\"\024\n\022CallDa" +
      "taFrameLogic\"\257\001\n\033CallObjectManipulationL" +
      "ogic\022\032\n\010objectId\030\001 \001(\005R\010objectId\022\034\n\tnewO" +
      "bject\030\002 \001(\010R\tnewObject\022\"\n\014deleteObject\030\003" +
      " \001(\010R\014deleteObject\022\036\n\nmethodName\030\004 \001(\tR\n" +
      "methodName\022\022\n\004args\030\005 \003(\tR\004argsB \n\034com.ss" +
      "inchenko.example.protoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_CallCommandLikeLogic_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CallCommandLikeLogic_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CallCommandLikeLogic_descriptor,
        new java.lang.String[] { "ParamA", "ParamB", "ParamC", });
    internal_static_CallDataFrameLogic_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CallDataFrameLogic_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CallDataFrameLogic_descriptor,
        new java.lang.String[] { });
    internal_static_CallObjectManipulationLogic_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_CallObjectManipulationLogic_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CallObjectManipulationLogic_descriptor,
        new java.lang.String[] { "ObjectId", "NewObject", "DeleteObject", "MethodName", "Args", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
